// Country flag emojis mapping
export const countryFlags: Record<string, string> = {
  "Egypt": "🇪🇬",
  "Tunisia": "🇹🇳",
  "Morocco": "🇲🇦",
  "South Korea": "🇰🇷",
  "Korea": "🇰🇷",
  "Iran": "🇮🇷",
  "Turkey": "🇹🇷",
  "Jordan": "🇯🇴",
  "Saudi Arabia": "🇸🇦",
  "Spain": "🇪🇸",
  "France": "🇫🇷",
  "Germany": "🇩🇪",
  "Italy": "🇮🇹",
  "United Kingdom": "🇬🇧",
  "UK": "🇬🇧",
  "United States": "🇺🇸",
  "USA": "🇺🇸",
  "Canada": "🇨🇦",
  "Australia": "🇦🇺",
  "Japan": "🇯🇵",
  "China": "🇨🇳",
  "Russia": "🇷🇺",
  "Brazil": "🇧🇷",
  "Mexico": "🇲🇽",
  "Argentina": "🇦🇷",
  "Chile": "🇨🇱",
  "Colombia": "🇨🇴",
  "Peru": "🇵🇪",
  "Venezuela": "🇻🇪",
  "Thailand": "🇹🇭",
  "Philippines": "🇵🇭",
  "Indonesia": "🇮🇩",
  "Malaysia": "🇲🇾",
  "Singapore": "🇸🇬",
  "Vietnam": "🇻🇳",
  "India": "🇮🇳",
  "Pakistan": "🇵🇰",
  "Bangladesh": "🇧🇩",
  "Sri Lanka": "🇱🇰",
  "Nepal": "🇳🇵",
  "Afghanistan": "🇦🇫",
  "Iraq": "🇮🇶",
  "Syria": "🇸🇾",
  "Lebanon": "🇱🇧",
  "Palestine": "🇵🇸",
  "Israel": "🇮🇱",
  "UAE": "🇦🇪",
  "Qatar": "🇶🇦",
  "Kuwait": "🇰🇼",
  "Bahrain": "🇧🇭",
  "Oman": "🇴🇲",
  "Yemen": "🇾🇪",
  "Algeria": "🇩🇿",
  "Libya": "🇱🇾",
  "Sudan": "🇸🇩",
  "Ethiopia": "🇪🇹",
  "Kenya": "🇰🇪",
  "Nigeria": "🇳🇬",
  "South Africa": "🇿🇦",
  "Ghana": "🇬🇭",
  "Senegal": "🇸🇳",
  "Cameroon": "🇨🇲",
  "Ivory Coast": "🇨🇮",
  "Mali": "🇲🇱",
  "Burkina Faso": "🇧🇫",
  "Niger": "🇳🇪",
  "Chad": "🇹🇩",
  "Congo": "🇨🇬",
  "Angola": "🇦🇴",
  "Zambia": "🇿🇲",
  "Zimbabwe": "🇿🇼",
  "Botswana": "🇧🇼",
  "Namibia": "🇳🇦",
  "Mozambique": "🇲🇿",
  "Madagascar": "🇲🇬",
  "Mauritius": "🇲🇺",
  "Seychelles": "🇸🇨",
  "Comoros": "🇰🇲",
  "Djibouti": "🇩🇯",
  "Eritrea": "🇪🇷",
  "Somalia": "🇸🇴",
  "Uganda": "🇺🇬",
  "Tanzania": "🇹🇿",
  "Rwanda": "🇷🇼",
  "Burundi": "🇧🇮",
  "Malawi": "🇲🇼",
  "Lesotho": "🇱🇸",
  "Swaziland": "🇸🇿",
  "Eswatini": "🇸🇿",
  "Netherlands": "🇳🇱",
  "Belgium": "🇧🇪",
  "Luxembourg": "🇱🇺",
  "Switzerland": "🇨🇭",
  "Austria": "🇦🇹",
  "Czech Republic": "🇨🇿",
  "Slovakia": "🇸🇰",
  "Poland": "🇵🇱",
  "Hungary": "🇭🇺",
  "Romania": "🇷🇴",
  "Bulgaria": "🇧🇬",
  "Serbia": "🇷🇸",
  "Croatia": "🇭🇷",
  "Slovenia": "🇸🇮",
  "Bosnia and Herzegovina": "🇧🇦",
  "Montenegro": "🇲🇪",
  "North Macedonia": "🇲🇰",
  "Albania": "🇦🇱",
  "Greece": "🇬🇷",
  "Cyprus": "🇨🇾",
  "Malta": "🇲🇹",
  "Portugal": "🇵🇹",
  "Andorra": "🇦🇩",
  "Monaco": "🇲🇨",
  "San Marino": "🇸🇲",
  "Vatican City": "🇻🇦",
  "Liechtenstein": "🇱🇮",
  "Iceland": "🇮🇸",
  "Norway": "🇳🇴",
  "Sweden": "🇸🇪",
  "Denmark": "🇩🇰",
  "Finland": "🇫🇮",
  "Estonia": "🇪🇪",
  "Latvia": "🇱🇻",
  "Lithuania": "🇱🇹",
  "Belarus": "🇧🇾",
  "Ukraine": "🇺🇦",
  "Moldova": "🇲🇩",
  "Georgia": "🇬🇪",
  "Armenia": "🇦🇲",
  "Azerbaijan": "🇦🇿",
  "Kazakhstan": "🇰🇿",
  "Kyrgyzstan": "🇰🇬",
  "Tajikistan": "🇹🇯",
  "Turkmenistan": "🇹🇲",
  "Uzbekistan": "🇺🇿",
  "Mongolia": "🇲🇳",
  "North Korea": "🇰🇵",
  "Taiwan": "🇹🇼",
  "Hong Kong": "🇭🇰",
  "Macau": "🇲🇴"
};

export function getCountryFlag(nationality: string): string {
  return countryFlags[nationality] || "🏴";
}

export function getCountryFlagWithFallback(nationality: string): string {
  const flag = countryFlags[nationality];
  if (flag) {
    return flag;
  }
  
  // Try to find partial matches for common variations
  const lowerNationality = nationality.toLowerCase();
  for (const [country, flag] of Object.entries(countryFlags)) {
    if (country.toLowerCase().includes(lowerNationality) || lowerNationality.includes(country.toLowerCase())) {
      return flag;
    }
  }
  
  return "🏴"; // Black flag as fallback
}